
USE mydb;
CREATE TABLE STUDENT2
(SNO INT(5),
SNAME VARCHAR(20),
MARKS INT(5));

INSERT INTO student2 VALUES(101,'KIRAN',80);
INSERT INTO student2 VALUES(102,'RAHUL',72);
INSERT INTO student2 VALUES(103,'ROHAN',95);
INSERT INTO student2 VALUES(104,'VARUN',60);
SELECT * FROM student2;
SELECT SNO FROM student2;
SELECT SNO SLNO FROM student2;
SELECT MARKS+5 FROM student2;
